[env]
OUT_DIR = "somedir"

[package]
name = "aska"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/serverside/main.rs"

[dependencies]
log = "0.4.8"
env_logger = "0.11.5"
hyper = { version = "1.4.1", features = ["full"] }
tokio = { version = "1.39.2", features = ["full"] }
http-body-util = "0.1.2"
hyper-util = { version = "0.1.6", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
